theme: jekyll-theme-midnight

# Setup
title:               Sathishkumar's blog
url:                 http://tsathishkumar.github.io

# About/contact
author:
  name:              Sathishkumar Thangavel
  email:             tsatiz@gmail.com

plugins:  [github-pages]
timezone: Asia/Kolkata
